### ISSUE TITLE
Settings in the first window and/or multiple mode selections for worldwide users

### ISSUE THREAD

**Issue by redjacketKR** [gimbal-ghost/gimbal-ghost#49]
Hi,

One movie can be viewed by mode1 and mode2 users so I wanted to select mode1 and mode2 as default
Can multiple selection be done? and for less clicking, option window can be located on the right side in the main window like edge radio box. 
If I may add one more , I can edit the color of the stick in the video editor, but If we can choose from "gimbal ghost" It would be great. 

personally, I changed slightly and it generate the name as 
" X38_30_20240315_201519 flight 2 mode2 fps 30.mov " 

and It would be like,

"X38_30_20240315_201519 flight 2 mode1 fps 30 red.mov"
"X38_30_20240315_201519 flight 2 mode2 fps 30 blue.mov"

![image 1](https://github.com/gimbal-ghost/gimbal-ghost/assets/37834299/1635a5ea-2440-40f1-8910-4ee50f8dac0c)

https://github.com/gimbal-ghost/gimbal-ghost/assets/37834299/273f9ada-1268-40d1-9a9e-1d505062e44a

**Comment by joshuadavidson** [comment]
Thanks for reaching out with some suggestions. I'll address each of our suggestions one by one:

1. Multiple mode selection
With gimbal ghost being optimized for the fastest processing time, if you want to render two different modes you can just run twice with two different modes selected. If this is something a large body of users want I can look into implementing.

2. Moving the options window
For most users the options will be set once and never touched again. I understand that in your specific use case this might not work but I want to avoid cluttering the UI. If this is something you desire you can freely fork the codebase and tweak to your heart's desire. 

3. Changing stick color
This is a technical limitation due to the design choices made in favoring performance over customization. All of the frames are prerendered so any change to the 3D model (colors, shapes, sizes, etc.) would have to prerendered and uploaded for each customization. If you're feeling adventurous you can use the https://github.com/gimbal-ghost/gg-default-gimbals repo to prerender your own style and then just replace the existing ones found in `%ProgramFiles%\Gimbal Ghost\resources\default-gimbals`. 

I'm closing this issue, but feel free to continue discussion if you feel warranted.

**Comment by redjacketKR** [comment]
Thanks for your answer. I will look into it.
